-- DevScribe Database Schema
-- Run this in Supabase SQL Editor

-- ============================================
-- 1. USER PROFILES TABLE
-- ============================================
-- Stores additional user info linked to Supabase auth

CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    github_username TEXT NOT NULL,
    github_avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Users can only read/update their own profile
CREATE POLICY "Users can view own profile"
    ON user_profiles FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
    ON user_profiles FOR UPDATE
    USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
    ON user_profiles FOR INSERT
    WITH CHECK (auth.uid() = id);

-- ============================================
-- 2. CONNECTED REPOSITORIES TABLE
-- ============================================
-- Stores GitHub repositories connected by users

CREATE TABLE IF NOT EXISTS connected_repositories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    github_repo_id BIGINT NOT NULL,
    repo_name TEXT NOT NULL,
    repo_full_name TEXT NOT NULL,
    repo_url TEXT NOT NULL,
    default_branch TEXT DEFAULT 'main',
    is_private BOOLEAN DEFAULT false,
    connected_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Prevent duplicate connections
    UNIQUE(user_id, github_repo_id)
);

-- Enable RLS
ALTER TABLE connected_repositories ENABLE ROW LEVEL SECURITY;

-- Users can only access their own repositories
CREATE POLICY "Users can view own repositories"
    ON connected_repositories FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own repositories"
    ON connected_repositories FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own repositories"
    ON connected_repositories FOR DELETE
    USING (auth.uid() = user_id);

-- Index for faster user lookups
CREATE INDEX idx_connected_repos_user_id ON connected_repositories(user_id);

-- ============================================
-- 3. GENERATED DOCUMENTS TABLE
-- ============================================
-- Stores changelogs and READMEs generated by the app

CREATE TYPE doc_type AS ENUM ('changelog', 'readme');

CREATE TABLE IF NOT EXISTS generated_documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    repository_id UUID NOT NULL REFERENCES connected_repositories(id) ON DELETE CASCADE,
    doc_type doc_type NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE generated_documents ENABLE ROW LEVEL SECURITY;

-- Users can only access their own documents
CREATE POLICY "Users can view own documents"
    ON generated_documents FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own documents"
    ON generated_documents FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own documents"
    ON generated_documents FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own documents"
    ON generated_documents FOR DELETE
    USING (auth.uid() = user_id);

-- Indexes for common queries
CREATE INDEX idx_documents_user_id ON generated_documents(user_id);
CREATE INDEX idx_documents_repository_id ON generated_documents(repository_id);
CREATE INDEX idx_documents_doc_type ON generated_documents(doc_type);
CREATE INDEX idx_documents_created_at ON generated_documents(created_at DESC);

-- ============================================
-- 4. UPDATED_AT TRIGGER
-- ============================================
-- Automatically update updated_at timestamp

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_generated_documents_updated_at
    BEFORE UPDATE ON generated_documents
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 5. AUTO-CREATE USER PROFILE ON SIGNUP
-- ============================================
-- Trigger to create user_profile when a new user signs up via GitHub

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO user_profiles (id, github_username, github_avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'user_name', NEW.raw_user_meta_data->>'preferred_username', 'unknown'),
        NEW.raw_user_meta_data->>'avatar_url'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION handle_new_user();